[package]
name = "tmpl-askama_git"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
tmpls = { version = "*", path = ".." }

askama = { version = "*", git = "https://github.com/askama-rs/askama", branch = "master" }
