[licenses]
version = 2
allow = ["Apache-2.0", "BSL-1.0", "MIT", "Unicode-3.0", "Zlib"]
private = { ignore = true }

[sources]
allow-git = [
    "https://github.com/askama-rs/askama",
]

[advisories]
ignore = [
    # `proc-macro-error` is unmaintained, but still used in yew
    "RUSTSEC-2024-0370",
    # `paste` is unmaintained, but still used in leptos
    "RUSTSEC-2024-0436",
]
