[licenses]
version = 2
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
private = { ignore = true }

[advisories]
ignore = [
    # `proc-macro-error` is unmaintained, but still used by `maud_macros`
    "RUSTSEC-2024-0370",
]

[sources]
allow-git = [
    "https://github.com/rinja-rs/rinja",
]
